#ifndef DECLARE_CSR
#define DECLARE_CSR(name, number)  number;
#endif

#define CSR_PMACFG0 0x4a0
#define CSR_PMACFG1 0x4a1
#define CSR_PMACFG2 0x4a2
#define CSR_PMACFG3 0x4a3
#define CSR_PMAADDR0 0x4b0
#define CSR_PMAADDR1 0x4b1
#define CSR_PMAADDR2 0x4b2
#define CSR_PMAADDR3 0x4b3
#define CSR_PMAADDR4 0x4b4
#define CSR_PMAADDR5 0x4b5
#define CSR_PMAADDR6 0x4b6
#define CSR_PMAADDR7 0x4b7
#define CSR_PMAADDR8 0x4b8
#define CSR_PMAADDR9 0x4b9
#define CSR_PMAADDR10 0x4ba
#define CSR_PMAADDR11 0x4bb
#define CSR_PMAADDR12 0x4bc
#define CSR_PMAADDR13 0x4bd
#define CSR_PMAADDR14 0x4be
#define CSR_PMAADDR15 0x4bf


DECLARE_CSR(pmacfg0, CSR_PMACFG0)
DECLARE_CSR(pmacfg1, CSR_PMACFG1)
DECLARE_CSR(pmacfg2, CSR_PMACFG2)
DECLARE_CSR(pmacfg3, CSR_PMACFG3)
DECLARE_CSR(pmaaddr0, CSR_PMAADDR0)
DECLARE_CSR(pmaaddr1, CSR_PMAADDR1)
DECLARE_CSR(pmaaddr2, CSR_PMAADDR2)
DECLARE_CSR(pmaaddr3, CSR_PMAADDR3)
DECLARE_CSR(pmaaddr4, CSR_PMAADDR4)
DECLARE_CSR(pmaaddr5, CSR_PMAADDR5)
DECLARE_CSR(pmaaddr6, CSR_PMAADDR6)
DECLARE_CSR(pmaaddr7, CSR_PMAADDR7)
DECLARE_CSR(pmaaddr8, CSR_PMAADDR8)
DECLARE_CSR(pmaaddr9, CSR_PMAADDR9)
DECLARE_CSR(pmaaddr10, CSR_PMAADDR10)
DECLARE_CSR(pmaaddr11, CSR_PMAADDR11)
DECLARE_CSR(pmaaddr12, CSR_PMAADDR12)
DECLARE_CSR(pmaaddr13, CSR_PMAADDR13)
DECLARE_CSR(pmaaddr14, CSR_PMAADDR14)
DECLARE_CSR(pmaaddr15, CSR_PMAADDR15)


